### PR TITLE
Version2.2

### PR DESCRIPTION
**Pull request by bjbvoesenek**
Add relative expression (not normalized) calculation. Data will be stored in an Excel file and plotted in a PDF file

### CODE REVIEW

**Comment by bjbvoesenek** [comment]
Thanks for updating the website with version 2.1!

Next version is already waiting :) This will be the definitive version for a while I hope

**Review by ifokkema — APPROVED** [review]
Looks good to me! Will you merge it, or do you want me to merge it? I'll add the tag after merging and update the website.

**Comment by bjbvoesenek** [comment]
You can merge it if you want, thanks!

**Comment by ifokkema** [comment]
Merged, tagged, updated on the website, and tested! Everything good!

**Pull request merged**
